#!/bin/sh
enable(){
	if [ ! -f /etc/crontabs/root ]; then
		 echo "*/5 * * * * myddns all" >/etc/crontabs/root
	else
		if [  ! "$(cat /etc/crontabs/root |wc -l)" = "0" -a  -z "$(cat /etc/crontabs/root |grep myddns)" ]; then
			sed -i '1i*/5 * * * * myddns all' /etc/crontabs/root
		else
			echo "*/5 * * * * myddns all" >/etc/crontabs/root
		fi
	fi
	echo '[ "$ACTION" = "ifup" ] && {' > /etc/hotplug.d/iface/99-myddns
	echo '	myddns $INTERFACE &' >>/etc/hotplug.d/iface/99-myddns
	echo '}' >>/etc/hotplug.d/iface/99-myddns
	/etc/init.d/cron reload
	        
}
disable(){
	sed -i '/myddns all/'d /etc/crontabs/root
	[ -f /etc/hotplug.d/iface/99-myddns ] && rm /etc/hotplug.d/iface/99-myddns
	[ "$(cat /etc/crontabs/root |wc -l)" = "0" ] && rm /etc/crontabs/root
	/etc/init.d/cron reload
}
restart(){
	myddns all
}
eval $1
