#!/bin/sh /etc/rc.common
. /lib/hdwifi.sh
local board=$(hdwifi_get_board)

START=99
start(){
    [ "${board}" == "hc5661" -o "${board}" == "r6830" ] && {
    	/usr/sbin/hc5661_internet.sh &
    }
}
stop() {
    logger "stop"
}
