#!/bin/sh /etc/rc.common
START=99
start(){
    if [ ! -f /etc/crontabs/root ]; then
        echo "*/5 * * * * /usr/sbin/whitelist.sh update" >/etc/crontabs/root
    else
		if [  ! "$(cat /etc/crontabs/root |wc -l)" = "0" -a  -z "$(cat /etc/crontabs/root |grep whitelist)" ]; then
			sed -i '1i*/5 * * * * /usr/sbin/whitelist.sh update' /etc/crontabs/root
		else
			echo "*/5 * * * * /usr/sbin/whitelist.sh update" >/etc/crontabs/root
		fi
	fi
    /etc/init.d/cron reload
}
stop() {
	sed -i  '/whitelist.sh/'d /etc/crontabs/root
    /etc/init.d/cron reload
}
