#!/bin/sh /etc/rc.common
START=49
start(){
    if [ ! -f /etc/crontabs/root ]; then
        echo "0 2 * * * /usr/sbin/autoupgrade.sh" >/etc/crontabs/root
    else
		if [ -z "$(cat /etc/crontabs/root |grep autoupgrade)" ]; then
			sed -i '1i0 2 * * * /usr/sbin/autoupgrade.sh' /etc/crontabs/root
		fi
	fi
}
stop() {
	sed -i  '/autoupgrade.sh/'d /etc/crontabs/root
}
